//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web1.Areas.Masters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_vendor
    {
        public int TRANSPORTERID { get; set; }
        public string Company_name { get; set; }
    }
}
